#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ActivatableMovieWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ActivatableMovieWidget.ActivatableMovieWidget_C
// 0x0010 (0x03C8 - 0x03B8)
class UActivatableMovieWidget_C final : public UFortActivatableVideoPanel
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USafeZone*                              MainSafeZone;                                      // 0x03C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ActivatableMovieWidget(int32 EntryPoint);
	void OnActivated();
	void OnDeactivated();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActivatableMovieWidget_C">();
	}
	static class UActivatableMovieWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivatableMovieWidget_C>();
	}
};

}

