#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_CameraLens_SpookyMist_Dive

#include "Basic.hpp"

#include "B_CameraLens_SpookyMist_Dive_classes.hpp"
#include "B_CameraLens_SpookyMist_Dive_parameters.hpp"


namespace SDK
{

// Function B_CameraLens_SpookyMist_Dive.B_CameraLens_SpookyMist_Dive_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AB_CameraLens_SpookyMist_Dive_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_CameraLens_SpookyMist_Dive_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_CameraLens_SpookyMist_Dive.B_CameraLens_SpookyMist_Dive_C.ExecuteUbergraph_B_CameraLens_SpookyMist_Dive
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_CameraLens_SpookyMist_Dive_C::ExecuteUbergraph_B_CameraLens_SpookyMist_Dive(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_CameraLens_SpookyMist_Dive_C", "ExecuteUbergraph_B_CameraLens_SpookyMist_Dive");

	Params::B_CameraLens_SpookyMist_Dive_C_ExecuteUbergraph_B_CameraLens_SpookyMist_Dive Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

