#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: B_Melee_Torch

#include "Basic.hpp"

#include "B_Melee_Torch_classes.hpp"
#include "B_Melee_Torch_parameters.hpp"


namespace SDK
{

// Function B_Melee_Torch.B_Melee_Torch_C.ExecuteUbergraph_B_Melee_Torch
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AB_Melee_Torch_C::ExecuteUbergraph_B_Melee_Torch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Melee_Torch_C", "ExecuteUbergraph_B_Melee_Torch");

	Params::B_Melee_Torch_C_ExecuteUbergraph_B_Melee_Torch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Melee_Torch.B_Melee_Torch_C.OnWeaponVisibilityChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bVisible                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void AB_Melee_Torch_C::OnWeaponVisibilityChanged(bool bVisible)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Melee_Torch_C", "OnWeaponVisibilityChanged");

	Params::B_Melee_Torch_C_OnWeaponVisibilityChanged Parms{};

	Parms.bVisible = bVisible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function B_Melee_Torch.B_Melee_Torch_C.K2_OnUnEquip
// (Event, Public, BlueprintEvent)

void AB_Melee_Torch_C::K2_OnUnEquip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Melee_Torch_C", "K2_OnUnEquip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Melee_Torch.B_Melee_Torch_C.OnWeaponAttached
// (Event, Public, BlueprintEvent)

void AB_Melee_Torch_C::OnWeaponAttached()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Melee_Torch_C", "OnWeaponAttached");

	UObject::ProcessEvent(Func, nullptr);
}


// Function B_Melee_Torch.B_Melee_Torch_C.Play Torch Audio Loop
// (BlueprintCallable, BlueprintEvent)

void AB_Melee_Torch_C::Play_Torch_Audio_Loop()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("B_Melee_Torch_C", "Play Torch Audio Loop");

	UObject::ProcessEvent(Func, nullptr);
}

}

