#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Boardwalk_Archway

#include "Basic.hpp"

#include "Parent_BuildingWall_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Boardwalk_Archway.Boardwalk_Archway_C
// 0x0000 (0x0C58 - 0x0C58)
class ABoardwalk_Archway_C final : public AParent_BuildingWall_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Boardwalk_Archway_C">();
	}
	static class ABoardwalk_Archway_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABoardwalk_Archway_C>();
	}
};

}

