#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: BP_ZippyTroutTrap_Floor

#include "Basic.hpp"

#include "BP_ZippyTroutTrap_Floor_classes.hpp"
#include "BP_ZippyTroutTrap_Floor_parameters.hpp"


namespace SDK
{

// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.ExecuteUbergraph_BP_ZippyTroutTrap_Floor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ZippyTroutTrap_Floor_C::ExecuteUbergraph_BP_ZippyTroutTrap_Floor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "ExecuteUbergraph_BP_ZippyTroutTrap_Floor");

	Params::BP_ZippyTroutTrap_Floor_C_ExecuteUbergraph_BP_ZippyTroutTrap_Floor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.ReceiveDestroyed
// (Event, Public, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::ReceiveDestroyed()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "ReceiveDestroyed");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.Jiggle
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Vector                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ZippyTroutTrap_Floor_C::Jiggle(const struct FVector& Vector)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "Jiggle");

	Params::BP_ZippyTroutTrap_Floor_C_Jiggle Parms{};

	Parms.Vector = std::move(Vector);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.MuzzleFire
// (Net, NetMulticast, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FName                             Socket_Name                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ZippyTroutTrap_Floor_C::MuzzleFire(class FName Socket_Name)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "MuzzleFire");

	Params::BP_ZippyTroutTrap_Floor_C_MuzzleFire Parms{};

	Parms.Socket_Name = Socket_Name;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.OnInitTeam
// (Event, Protected, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::OnInitTeam()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "OnInitTeam");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.OnWorldReady
// (Event, Public, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::OnWorldReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "OnWorldReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.GameplayCue.Abilities.Activation.Traps.ActivateTrap
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EGameplayCueEvent                       EventType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayCueParameters&    Parameters                                             (BlueprintVisible, BlueprintReadOnly, Parm, ContainsInstancedReference)

void ABP_ZippyTroutTrap_Floor_C::GameplayCue_Abilities_Activation_Traps_ActivateTrap(EGameplayCueEvent EventType, const struct FGameplayCueParameters& Parameters)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "GameplayCue.Abilities.Activation.Traps.ActivateTrap");

	Params::BP_ZippyTroutTrap_Floor_C_GameplayCue_Abilities_Activation_Traps_ActivateTrap Parms{};

	Parms.EventType = EventType;
	Parms.Parameters = std::move(Parameters);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.OnFinishedBuilding
// (Event, Public, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::OnFinishedBuilding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "OnFinishedBuilding");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.OnPlaced
// (Event, Public, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::OnPlaced()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "OnPlaced");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.OnReloadEnd
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::OnReloadEnd()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "OnReloadEnd");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C. ChangeToFriendlyMaterial
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::_ChangeToFriendlyMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", " ChangeToFriendlyMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.ChangeToNormalMaterial
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::ChangeToNormalMaterial()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "ChangeToNormalMaterial");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ZippyTroutTrap_Floor.BP_ZippyTroutTrap_Floor_C.OnRep_bIsFinishedBuilding
// (BlueprintCallable, BlueprintEvent)

void ABP_ZippyTroutTrap_Floor_C::OnRep_bIsFinishedBuilding()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ZippyTroutTrap_Floor_C", "OnRep_bIsFinishedBuilding");

	UObject::ProcessEvent(Func, nullptr);
}

}

