#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Device_Context_EliminationZone

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Device_Context_EliminationZone.Device_Context_EliminationZone_C
// 0x0000 (0x0C80 - 0x0C80)
class ADevice_Context_EliminationZone_C final : public ABuildingTrap
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Device_Context_EliminationZone_C">();
	}
	static class ADevice_Context_EliminationZone_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ADevice_Context_EliminationZone_C>();
	}
};

}

