#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_Athena_JollyRascal_PlayerDamage_Porta

#include "Basic.hpp"

#include "GE_Athena_JollyRascal_PlayerDamage_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_Athena_JollyRascal_PlayerDamage_Porta.GE_Athena_JollyRascal_PlayerDamage_Porta_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_Athena_JollyRascal_PlayerDamage_Porta_C final : public UGE_Athena_JollyRascal_PlayerDamage_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_Athena_JollyRascal_PlayerDamage_Porta_C">();
	}
	static class UGE_Athena_JollyRascal_PlayerDamage_Porta_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_Athena_JollyRascal_PlayerDamage_Porta_C>();
	}
};

}

