#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GE_OstrichPassive

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_OstrichPassive.GE_OstrichPassive_C
// 0x0000 (0x05F0 - 0x05F0)
class UGE_OstrichPassive_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_OstrichPassive_C">();
	}
	static class UGE_OstrichPassive_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_OstrichPassive_C>();
	}
};

}

