#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: OptionsMenuFireModeButton

#include "Basic.hpp"

#include "OptionsMenuFireModeButton_classes.hpp"
#include "OptionsMenuFireModeButton_parameters.hpp"


namespace SDK
{

// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.ExecuteUbergraph_OptionsMenuFireModeButton
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::ExecuteUbergraph_OptionsMenuFireModeButton(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "ExecuteUbergraph_OptionsMenuFireModeButton");

	Params::OptionsMenuFireModeButton_C_ExecuteUbergraph_OptionsMenuFireModeButton Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.BndEvt__ButtonTouchTooltip_K2Node_ComponentBoundEvent_11_CommonButtonClicked__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UCommonButton*                    Button                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::BndEvt__ButtonTouchTooltip_K2Node_ComponentBoundEvent_11_CommonButtonClicked__DelegateSignature(class UCommonButton* Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "BndEvt__ButtonTouchTooltip_K2Node_ComponentBoundEvent_11_CommonButtonClicked__DelegateSignature");

	Params::OptionsMenuFireModeButton_C_BndEvt__ButtonTouchTooltip_K2Node_ComponentBoundEvent_11_CommonButtonClicked__DelegateSignature Parms{};

	Parms.Button = Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UOptionsMenuFireModeButton_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.BP_OnEntryReleased
// (Event, Protected, BlueprintEvent)

void UOptionsMenuFireModeButton_C::BP_OnEntryReleased()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "BP_OnEntryReleased");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.CenterOnWidget
// (Event, Public, BlueprintCallable, BlueprintEvent)

void UOptionsMenuFireModeButton_C::CenterOnWidget()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "CenterOnWidget");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.BP_OnItemExpansionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsExpanded                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOptionsMenuFireModeButton_C::BP_OnItemExpansionChanged(bool bIsExpanded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "BP_OnItemExpansionChanged");

	Params::OptionsMenuFireModeButton_C_BP_OnItemExpansionChanged Parms{};

	Parms.bIsExpanded = bIsExpanded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.OnListItemObjectSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// class UObject*                          ListItemObject                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::OnListItemObjectSet(class UObject* ListItemObject)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "OnListItemObjectSet");

	Params::OptionsMenuFireModeButton_C_OnListItemObjectSet Parms{};

	Parms.ListItemObject = ListItemObject;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UOptionsMenuFireModeButton_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "OnMouseEnter");

	Params::OptionsMenuFireModeButton_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UOptionsMenuFireModeButton_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "OnMouseLeave");

	Params::OptionsMenuFireModeButton_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UOptionsMenuFireModeButton_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UOptionsMenuFireModeButton_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "BP_OnItemSelectionChanged");

	Params::OptionsMenuFireModeButton_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.UpdateSize
// (Public, BlueprintCallable, BlueprintEvent)

void UOptionsMenuFireModeButton_C::UpdateSize()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "UpdateSize");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.SetFontSize
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonTextBlock*                 Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   DefaultSize                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MobileSize                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::SetFontSize(class UCommonTextBlock* Text, int32 DefaultSize, int32 MobileSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "SetFontSize");

	Params::OptionsMenuFireModeButton_C_SetFontSize Parms{};

	Parms.Text = Text;
	Parms.DefaultSize = DefaultSize;
	Parms.MobileSize = MobileSize;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.HandleFireModeButtonClicked
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonButton*                    Common_Button                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::HandleFireModeButtonClicked(class UCommonButton* Common_Button)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "HandleFireModeButtonClicked");

	Params::OptionsMenuFireModeButton_C_HandleFireModeButtonClicked Parms{};

	Parms.Common_Button = Common_Button;

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.ShowTooltip
// (Public, BlueprintCallable, BlueprintEvent)

void UOptionsMenuFireModeButton_C::ShowTooltip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "ShowTooltip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.SetTooltipSize
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector2D&                 DefaultSize                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 MobileSize                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::SetTooltipSize(const struct FVector2D& DefaultSize, const struct FVector2D& MobileSize)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "SetTooltipSize");

	Params::OptionsMenuFireModeButton_C_SetTooltipSize Parms{};

	Parms.DefaultSize = std::move(DefaultSize);
	Parms.MobileSize = std::move(MobileSize);

	UObject::ProcessEvent(Func, &Parms);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.Hide Tooltip
// (Public, BlueprintCallable, BlueprintEvent)

void UOptionsMenuFireModeButton_C::Hide_Tooltip()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "Hide Tooltip");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.On_MenuAnchorSettingDescription_GetMenuContent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UOptionsMenuFireModeButton_C::On_MenuAnchorSettingDescription_GetMenuContent_0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "On_MenuAnchorSettingDescription_GetMenuContent_0");

	Params::OptionsMenuFireModeButton_C_On_MenuAnchorSettingDescription_GetMenuContent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.SetFireModeButtonText
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UOptionsMenuFireModeButton_C::SetFireModeButtonText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "SetFireModeButtonText");

	UObject::ProcessEvent(Func, nullptr);
}


// Function OptionsMenuFireModeButton.OptionsMenuFireModeButton_C.HandleWidgetDeactivated
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UCommonActivatablePanel*          ActivatableWidget                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UOptionsMenuFireModeButton_C::HandleWidgetDeactivated(class UCommonActivatablePanel* ActivatableWidget)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("OptionsMenuFireModeButton_C", "HandleWidgetDeactivated");

	Params::OptionsMenuFireModeButton_C_HandleWidgetDeactivated Parms{};

	Parms.ActivatableWidget = ActivatableWidget;

	UObject::ProcessEvent(Func, &Parms);
}

}

