#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Parent_BuildingPropWall

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Parent_BuildingPropWall.Parent_BuildingPropWall_C
// 0x0000 (0x0B20 - 0x0B20)
class AParent_BuildingPropWall_C : public ABuildingPropWall
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Parent_BuildingPropWall_C">();
	}
	static class AParent_BuildingPropWall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AParent_BuildingPropWall_C>();
	}
};

}

