#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: ChallengeReward

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ChallengeReward.ChallengeReward_C
// 0x0000 (0x0238 - 0x0238)
class UChallengeReward_C final : public UAthenaChallengeRewardDisplay
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ChallengeReward_C">();
	}
	static class UChallengeReward_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChallengeReward_C>();
	}
};

}

