#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: GA_Athena_SilverBlazer_WithTrajectory_V2

#include "Basic.hpp"

#include "GA_Athena_UtilityGrenade_WithTrajectory_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_SilverBlazer_WithTrajectory_V2.GA_Athena_SilverBlazer_WithTrajectory_V2_C
// 0x0000 (0x0C98 - 0x0C98)
class UGA_Athena_SilverBlazer_WithTrajectory_V2_C final : public UGA_Athena_UtilityGrenade_WithTrajectory_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_SilverBlazer_WithTrajectory_V2_C">();
	}
	static class UGA_Athena_SilverBlazer_WithTrajectory_V2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_SilverBlazer_WithTrajectory_V2_C>();
	}
};

}

