#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Prop_Sign_NoDancing

#include "Basic.hpp"

#include "Parent_BuildingPropActor_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Prop_Sign_NoDancing.Prop_Sign_NoDancing_C
// 0x0000 (0x0BD8 - 0x0BD8)
class AProp_Sign_NoDancing_C final : public AParent_BuildingPropActor_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Prop_Sign_NoDancing_C">();
	}
	static class AProp_Sign_NoDancing_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProp_Sign_NoDancing_C>();
	}
};

}

