#pragma once

/*
* SDK generated by Dumper-8
*
* https://github.com/NotTacs/Dumper-8
*/

// Package: Athena_Tree_Medium_03_

#include "Basic.hpp"

#include "Parent_Tree_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Athena_Tree_Medium_03_.Athena_Tree_Medium_03__C
// 0x0000 (0x0BC0 - 0x0BC0)
class AAthena_Tree_Medium_03__C final : public AParent_Tree_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Athena_Tree_Medium_03__C">();
	}
	static class AAthena_Tree_Medium_03__C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAthena_Tree_Medium_03__C>();
	}
};

}

